# -*- coding: utf-8 -*-
"""Decision trees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mooDBJVTVUm-wSYqKs2aLYVHlqwT0PCI
"""

!pip install numpy==2.2.0
!pip install pandas==2.2.3
!pip install scikit-learn==1.6.0
!pip install matplotlib==3.9.3

!pip install --force-reinstall numpy

!pip uninstall -y numpy scikit-learn

!pip install numpy==1.24.4 scikit-learn==1.3.2

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics

# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv'
my_data =pd.read_csv(url)
my_data

my_data.info()

label_encoder =LabelEncoder()
my_data['Sex'] =label_encoder.fit_transform(my_data['Sex'])
my_data['BP'] =label_encoder.fit_transform(my_data['BP'])
my_data['Cholesterol'] =label_encoder.fit_transform(my_data['Cholesterol'])
my_data['Drug'] =label_encoder.fit_transform(my_data['Drug'])
my_data

my_data.isnull().sum()

category_counts =my_data['Drug'].value_counts()
plt.bar(category_counts.index,category_counts.values,color='red')
plt.xlabel('Drug')
plt.ylabel('Count')
plt.title('Category Distribution')
plt.xticks(rotation=45)
plt.show()

